#include "bit_analyze/bounded_structural_fingerprint.hpp"
#include <algorithm>
#include <stdexcept>\n#include <limits>
namespace bit_analyze {
namespace {
std::uint64_t mix64(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
std::size_t bucket(std::uint64_t key,std::size_t count,std::uint64_t seed){return static_cast<std::size_t>(mix64(key^seed)%count);}
std::uint64_t transition_key(SymbolId a,SymbolId b){return mix64(static_cast<std::uint64_t>(a))^mix64(static_cast<std::uint64_t>(b)+0x9e3779b97f4a7c15ULL);}
double weighted_jaccard(const std::vector<std::uint64_t>&a,const std::vector<std::uint64_t>&b){if(a.size()!=b.size())return 0.0;long double mn=0,mx=0;for(std::size_t i=0;i<a.size();++i){mn+=std::min(a[i],b[i]);mx+=std::max(a[i],b[i]);}return mx?static_cast<double>(mn/mx):1.0;}
}
std::size_t BoundedStructuralFingerprint::storage_bytes() const noexcept{return (frequency.size()+regional_frequency.size()+transitions.size())*sizeof(std::uint64_t);}
BoundedStructuralFingerprintAccumulator::BoundedStructuralFingerprintAccumulator(std::uint64_t total_bytes,BoundedStructuralFingerprintConfig config){if(!config.frequency_buckets||!config.transition_buckets||!config.regions)throw std::invalid_argument("bounded fingerprint dimensions must be non-zero");fingerprint_.total_bytes=total_bytes;fingerprint_.config=config;fingerprint_.frequency.assign(config.frequency_buckets,0);fingerprint_.regional_frequency.assign(config.frequency_buckets*config.regions,0);fingerprint_.transitions.assign(config.transition_buckets,0);}
void BoundedStructuralFingerprintAccumulator::observe(const StructuralEvent&e){++fingerprint_.event_count;std::size_t region=0;if(fingerprint_.total_bytes>0)region=std::min(fingerprint_.config.regions-1,static_cast<std::size_t>((e.byte_offset/fingerprint_.total_bytes)*fingerprint_.config.regions+((e.byte_offset%fingerprint_.total_bytes)*fingerprint_.config.regions)/fingerprint_.total_bytes));for(auto id:e.relation_ids){const auto fb=bucket(static_cast<std::uint64_t>(id),fingerprint_.config.frequency_buckets,fingerprint_.config.hash_seed);++fingerprint_.frequency[fb];++fingerprint_.regional_frequency[region*fingerprint_.config.frequency_buckets+fb];if(have_previous_){const auto tb=bucket(transition_key(previous_,id),fingerprint_.config.transition_buckets,fingerprint_.config.hash_seed^0x5452414e534954ULL);++fingerprint_.transitions[tb];}previous_=id;have_previous_=true;}}
BoundedStructuralFingerprintAccumulator8::BoundedStructuralFingerprintAccumulator8(std::uint64_t total_bytes,BoundedStructuralFingerprintConfig config){if(!config.frequency_buckets||!config.transition_buckets||!config.regions)throw std::invalid_argument("bounded fingerprint dimensions must be non-zero");fingerprint_.total_bytes=total_bytes;fingerprint_.config=config;fingerprint_.frequency.assign(config.frequency_buckets,0);fingerprint_.regional_frequency.assign(config.frequency_buckets*config.regions,0);fingerprint_.transitions.assign(config.transition_buckets,0);}
void BoundedStructuralFingerprintAccumulator8::increment(std::vector<std::uint8_t>&counters,std::size_t index){if(counters[index]==255){for(auto&x:counters)x=static_cast<std::uint8_t>((static_cast<unsigned>(x)+1u)/2u);++fingerprint_.renormalizations;}++counters[index];}
void BoundedStructuralFingerprintAccumulator8::observe(const StructuralEvent&e){++fingerprint_.event_count;std::size_t region=0;if(fingerprint_.total_bytes>0)region=std::min(fingerprint_.config.regions-1,static_cast<std::size_t>((e.byte_offset/fingerprint_.total_bytes)*fingerprint_.config.regions+((e.byte_offset%fingerprint_.total_bytes)*fingerprint_.config.regions)/fingerprint_.total_bytes));for(auto id:e.relation_ids){const auto fb=bucket(static_cast<std::uint64_t>(id),fingerprint_.config.frequency_buckets,fingerprint_.config.hash_seed);increment(fingerprint_.frequency,fb);increment(fingerprint_.regional_frequency,region*fingerprint_.config.frequency_buckets+fb);if(have_previous_){const auto tb=bucket(transition_key(previous_,id),fingerprint_.config.transition_buckets,fingerprint_.config.hash_seed^0x5452414e534954ULL);increment(fingerprint_.transitions,tb);}previous_=id;have_previous_=true;}}
RollingStructuralFingerprintAccumulator8::RollingStructuralFingerprintAccumulator8(RollingStructuralFingerprintConfig config){auto&b=config.bounded;if(!b.frequency_buckets||!b.transition_buckets||!b.regions||!config.region_span_bytes)throw std::invalid_argument("rolling fingerprint dimensions and span must be non-zero");fingerprint_.config=config;fingerprint_.frequency.assign(b.frequency_buckets,0);fingerprint_.regional_frequency.assign(b.frequency_buckets*b.regions,0);fingerprint_.transitions.assign(b.transition_buckets,0);fingerprint_.region_epochs.assign(b.regions,std::numeric_limits<std::uint64_t>::max());}
void RollingStructuralFingerprintAccumulator8::increment(std::vector<std::uint8_t>&counters,std::size_t index){if(counters[index]==255){for(auto&x:counters)x=static_cast<std::uint8_t>((static_cast<unsigned>(x)+1u)/2u);++fingerprint_.renormalizations;}++counters[index];}
void RollingStructuralFingerprintAccumulator8::increment_region(std::size_t region,std::size_t bucket_index){const auto buckets=fingerprint_.config.bounded.frequency_buckets,base=region*buckets;auto&target=fingerprint_.regional_frequency[base+bucket_index];if(target==255){for(std::size_t i=0;i<buckets;++i){auto&x=fingerprint_.regional_frequency[base+i];x=static_cast<std::uint8_t>((static_cast<unsigned>(x)+1u)/2u);}++fingerprint_.renormalizations;}++fingerprint_.regional_frequency[base+bucket_index];}
void RollingStructuralFingerprintAccumulator8::observe(const StructuralEvent&e){if(have_event_&&e.byte_offset<last_offset_)throw std::invalid_argument("rolling fingerprint requires nondecreasing byte offsets");have_event_=true;last_offset_=e.byte_offset;++fingerprint_.event_count;const auto&b=fingerprint_.config.bounded;const auto epoch=e.byte_offset/fingerprint_.config.region_span_bytes;const auto region=static_cast<std::size_t>(epoch%b.regions);fingerprint_.latest_epoch=std::max(fingerprint_.latest_epoch,epoch);if(fingerprint_.region_epochs[region]!=epoch){if(fingerprint_.region_epochs[region]!=std::numeric_limits<std::uint64_t>::max())++fingerprint_.region_reuses;std::fill_n(fingerprint_.regional_frequency.begin()+region*b.frequency_buckets,b.frequency_buckets,0);fingerprint_.region_epochs[region]=epoch;}for(auto id:e.relation_ids){const auto fb=bucket(static_cast<std::uint64_t>(id),b.frequency_buckets,b.hash_seed);increment(fingerprint_.frequency,fb);increment_region(region,fb);if(have_previous_){const auto tb=bucket(transition_key(previous_,id),b.transition_buckets,b.hash_seed^0x5452414e534954ULL);increment(fingerprint_.transitions,tb);}previous_=id;have_previous_=true;}}
RollingStructuralStream8::RollingStructuralStream8(StructuralStream&stream,RollingStructuralFingerprintAccumulator8&accumulator):stream_(stream),accumulator_(accumulator){}
void RollingStructuralStream8::observe(const std::vector<StructuralEvent>&events){for(const auto&e:events)accumulator_.observe(e);}
std::vector<StructuralEvent> RollingStructuralStream8::push(const std::uint8_t*data,std::size_t size,const std::string&source_id){auto events=stream_.push(data,size,source_id);observe(events);return events;}
std::vector<StructuralEvent> RollingStructuralStream8::push(const std::vector<std::uint8_t>&data,const std::string&source_id){auto events=stream_.push(data,source_id);observe(events);return events;}
std::vector<StructuralEvent> RollingStructuralStream8::flush(const std::string&source_id){auto events=stream_.flush(source_id);observe(events);return events;}
BoundedStructuralFingerprint expand_bounded_structural_fingerprint(const BoundedStructuralFingerprint8&v){BoundedStructuralFingerprint o;o.version=v.version;o.total_bytes=v.total_bytes;o.event_count=v.event_count;o.config=v.config;o.frequency.assign(v.frequency.begin(),v.frequency.end());o.regional_frequency.assign(v.regional_frequency.begin(),v.regional_frequency.end());o.transitions.assign(v.transitions.begin(),v.transitions.end());return o;}
BoundedStructuralFingerprint make_bounded_structural_fingerprint(const std::vector<StructuralEvent>&events,std::uint64_t total_bytes,BoundedStructuralFingerprintConfig config){BoundedStructuralFingerprintAccumulator accumulator(total_bytes,config);for(const auto&e:events)accumulator.observe(e);return accumulator.fingerprint();}
StructuralSimilarity compare_bounded_structural_fingerprints(const BoundedStructuralFingerprint&a,const BoundedStructuralFingerprint&b){StructuralSimilarity s;if(a.config.frequency_buckets!=b.config.frequency_buckets||a.config.transition_buckets!=b.config.transition_buckets||a.config.regions!=b.config.regions||a.config.hash_seed!=b.config.hash_seed)return s;s.frequency=weighted_jaccard(a.frequency,b.frequency);s.transitions=weighted_jaccard(a.transitions,b.transitions);double sum=0;for(std::size_t r=0;r<a.config.regions;++r){std::vector<std::uint64_t>x(a.frequency.size()),y(b.frequency.size());const auto off=r*a.config.frequency_buckets;std::copy_n(a.regional_frequency.begin()+off,a.config.frequency_buckets,x.begin());std::copy_n(b.regional_frequency.begin()+off,b.config.frequency_buckets,y.begin());sum+=weighted_jaccard(x,y);}s.regional=sum/a.config.regions;s.combined=0.40*s.frequency+0.35*s.regional+0.25*s.transitions;return s;}
} // namespace bit_analyze
