#include "bit_analyze/bounded_structural_fingerprint.hpp"
#include <algorithm>
#include <stdexcept>
namespace bit_analyze {
namespace {
std::uint64_t mix64(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
std::size_t bucket(std::uint64_t key,std::size_t count,std::uint64_t seed){return static_cast<std::size_t>(mix64(key^seed)%count);}
std::uint64_t transition_key(SymbolId a,SymbolId b){return mix64(static_cast<std::uint64_t>(a))^mix64(static_cast<std::uint64_t>(b)+0x9e3779b97f4a7c15ULL);}
double weighted_jaccard(const std::vector<std::uint64_t>&a,const std::vector<std::uint64_t>&b){if(a.size()!=b.size())return 0.0;long double mn=0,mx=0;for(std::size_t i=0;i<a.size();++i){mn+=std::min(a[i],b[i]);mx+=std::max(a[i],b[i]);}return mx?static_cast<double>(mn/mx):1.0;}
}
std::size_t BoundedStructuralFingerprint::storage_bytes() const noexcept{return (frequency.size()+regional_frequency.size()+transitions.size())*sizeof(std::uint64_t);}
BoundedStructuralFingerprintAccumulator::BoundedStructuralFingerprintAccumulator(std::uint64_t total_bytes,BoundedStructuralFingerprintConfig config){if(!config.frequency_buckets||!config.transition_buckets||!config.regions)throw std::invalid_argument("bounded fingerprint dimensions must be non-zero");fingerprint_.total_bytes=total_bytes;fingerprint_.config=config;fingerprint_.frequency.assign(config.frequency_buckets,0);fingerprint_.regional_frequency.assign(config.frequency_buckets*config.regions,0);fingerprint_.transitions.assign(config.transition_buckets,0);}
void BoundedStructuralFingerprintAccumulator::observe(const StructuralEvent&e){++fingerprint_.event_count;std::size_t region=0;if(fingerprint_.total_bytes>0)region=std::min(fingerprint_.config.regions-1,static_cast<std::size_t>((e.byte_offset/fingerprint_.total_bytes)*fingerprint_.config.regions+((e.byte_offset%fingerprint_.total_bytes)*fingerprint_.config.regions)/fingerprint_.total_bytes));for(auto id:e.relation_ids){const auto fb=bucket(static_cast<std::uint64_t>(id),fingerprint_.config.frequency_buckets,fingerprint_.config.hash_seed);++fingerprint_.frequency[fb];++fingerprint_.regional_frequency[region*fingerprint_.config.frequency_buckets+fb];if(have_previous_){const auto tb=bucket(transition_key(previous_,id),fingerprint_.config.transition_buckets,fingerprint_.config.hash_seed^0x5452414e534954ULL);++fingerprint_.transitions[tb];}previous_=id;have_previous_=true;}}
BoundedStructuralFingerprintAccumulator8::BoundedStructuralFingerprintAccumulator8(std::uint64_t total_bytes,BoundedStructuralFingerprintConfig config){if(!config.frequency_buckets||!config.transition_buckets||!config.regions)throw std::invalid_argument("bounded fingerprint dimensions must be non-zero");fingerprint_.total_bytes=total_bytes;fingerprint_.config=config;fingerprint_.frequency.assign(config.frequency_buckets,0);fingerprint_.regional_frequency.assign(config.frequency_buckets*config.regions,0);fingerprint_.transitions.assign(config.transition_buckets,0);}
void BoundedStructuralFingerprintAccumulator8::increment(std::vector<std::uint8_t>&counters,std::size_t index){if(counters[index]==255){for(auto&x:counters)x=static_cast<std::uint8_t>((static_cast<unsigned>(x)+1u)/2u);++fingerprint_.renormalizations;}++counters[index];}
void BoundedStructuralFingerprintAccumulator8::observe(const StructuralEvent&e){++fingerprint_.event_count;std::size_t region=0;if(fingerprint_.total_bytes>0)region=std::min(fingerprint_.config.regions-1,static_cast<std::size_t>((e.byte_offset/fingerprint_.total_bytes)*fingerprint_.config.regions+((e.byte_offset%fingerprint_.total_bytes)*fingerprint_.config.regions)/fingerprint_.total_bytes));for(auto id:e.relation_ids){const auto fb=bucket(static_cast<std::uint64_t>(id),fingerprint_.config.frequency_buckets,fingerprint_.config.hash_seed);increment(fingerprint_.frequency,fb);increment(fingerprint_.regional_frequency,region*fingerprint_.config.frequency_buckets+fb);if(have_previous_){const auto tb=bucket(transition_key(previous_,id),fingerprint_.config.transition_buckets,fingerprint_.config.hash_seed^0x5452414e534954ULL);increment(fingerprint_.transitions,tb);}previous_=id;have_previous_=true;}}
BoundedStructuralFingerprint expand_bounded_structural_fingerprint(const BoundedStructuralFingerprint8&v){BoundedStructuralFingerprint o;o.version=v.version;o.total_bytes=v.total_bytes;o.event_count=v.event_count;o.config=v.config;o.frequency.assign(v.frequency.begin(),v.frequency.end());o.regional_frequency.assign(v.regional_frequency.begin(),v.regional_frequency.end());o.transitions.assign(v.transitions.begin(),v.transitions.end());return o;}
BoundedStructuralFingerprint make_bounded_structural_fingerprint(const std::vector<StructuralEvent>&events,std::uint64_t total_bytes,BoundedStructuralFingerprintConfig config){BoundedStructuralFingerprintAccumulator accumulator(total_bytes,config);for(const auto&e:events)accumulator.observe(e);return accumulator.fingerprint();}
StructuralSimilarity compare_bounded_structural_fingerprints(const BoundedStructuralFingerprint&a,const BoundedStructuralFingerprint&b){StructuralSimilarity s;if(a.config.frequency_buckets!=b.config.frequency_buckets||a.config.transition_buckets!=b.config.transition_buckets||a.config.regions!=b.config.regions||a.config.hash_seed!=b.config.hash_seed)return s;s.frequency=weighted_jaccard(a.frequency,b.frequency);s.transitions=weighted_jaccard(a.transitions,b.transitions);double sum=0;for(std::size_t r=0;r<a.config.regions;++r){std::vector<std::uint64_t>x(a.frequency.size()),y(b.frequency.size());const auto off=r*a.config.frequency_buckets;std::copy_n(a.regional_frequency.begin()+off,a.config.frequency_buckets,x.begin());std::copy_n(b.regional_frequency.begin()+off,b.config.frequency_buckets,y.begin());sum+=weighted_jaccard(x,y);}s.regional=sum/a.config.regions;s.combined=0.40*s.frequency+0.35*s.regional+0.25*s.transitions;return s;}
} // namespace bit_analyze
